### ISSUE TITLE
Alloy Compile Error

### ISSUE THREAD

**Issue by Pinesy** [dbankier/JAST#6]
Hi, I am getting an error when trying to run the command `grunt dev -p ios` and anything that's not `grunt build` or `ti build -p ios --appify`. The explicit ti build just gives me a screen with tiShadow, but not the actual application running. the application - fresh clone, globally installed as well as locally installed alloy/ti shadow/grunt-cli, as well as those in package.json

```
[INFO] [index.xml] view processing...
[INFO]   style:      "index.tss"
[INFO]   view:       "index.xml"
[INFO]   controller: "index.js"

/usr/local/lib/node_modules/alloy/Alloy/commands/compile/sourceMapper.js:99
		throw e;
		      ^
Error
    at new JS_Parse_Error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:656:9)
    at token_error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:664:9)
    at unexpected (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:670:9)
    at expr_atom (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1166:9)
    at maybe_unary (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1327:19)
    at expr_op (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1349:33)
    at expr_ops (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1362:16)
    at maybe_conditional (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1367:20)
[ERROR] Alloy Compile Error
```

**Comment by dbankier** [comment]
I _just_ reworked the `Gruntfile.js`.

Can you do the following:
 * clone the repo (again)
 * `npm install`
 * `grunt`
 * In a separate terminal window `ts server`
 * `ts build -p ios --appify`
 * `grunt dev -p ios`

I just ran through the steps myself.

**Comment by Pinesy** [comment]
Ok, deleted my copy, then recloned, npm installed, grunted, opened another tab with ts server. Once I do ti build -p ios --appify, I still get the same error. I have had this same error on two different macs.
```
± |master ✓| → ti build -p ios --appify
Titanium Command-Line Interface, CLI version 3.4.1, Titanium SDK version 3.5.0.GA
Copyright (c) 2012-2014, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

Wed Feb 11 2015 21:29:45 GMT-0500 (EST)

Operating System
  Name                        = Mac OS X
  Version                     = 10.10.2
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 17179869184

Node.js
  Node.js Version             = 0.10.34
  npm Version                 = 1.4.28

Titanium CLI
  CLI Version                 = 3.4.1

Titanium SDK
  SDK Version                 = 3.5.0.GA
  SDK Path                    = /Users/hal/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA
  Target Platform             = iphone

Command
  /usr/local/bin/node /usr/local/bin/ti build -p ios --appify

[INFO]  No device family specified, defaulting to universal
[INFO]  Found Titanium plugin id=ti.alloy version=1.0 
[INFO]  Deploy type: development
[INFO]  Building for target: simulator
[INFO]  Building using iOS SDK: 8.1
[INFO]  Building for iOS Simulator: iPhone 4s
[INFO]  Building for device family: universal
[INFO]  Minimum iOS version: 7.0
[INFO]  Debugging disabled
[INFO]  Profiler disabled
[INFO]  Forcing rebuild: /Users/hal/Repositories/apps/JAST/build/iphone/build-manifest.json does not exist
[INFO]  Initiating prepare phase
[INFO]  Found Alloy app in /Users/hal/Repositories/apps/JAST/app
[INFO]  Executing Alloy compile: /usr/local/bin/node /usr/local/bin/alloy compile /Users/hal/Repositories/apps/JAST/app --config platform=ios,version=0,simtype=none,devicefamily=universal,deploytype=development,target=simulator
[INFO]   [config.json] regenerating CFG.js from config.json...
[INFO]  ----- MVC GENERATION -----
[INFO]  [app.tss] global style processing...
[INFO]  [global style] writing to cache...
[INFO]  [view.xml] nl.fokkezb.loading view processing...
[INFO]    style:      "view.tss"
[INFO]    view:       "view.xml"
[INFO]    controller: "view.js"
[INFO]    created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/view.js"
[INFO]    created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/view.js"
[INFO]  [widget.xml] nl.fokkezb.loading view processing...
[INFO]    view:       "widget.xml"
[INFO]    controller: "widget.js"
[INFO]    created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/widget.js"
[INFO]    created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/widget.js"
[INFO]  [window.xml] nl.fokkezb.loading view processing...
[INFO]    style:      "window.tss"
[INFO]    view:       "window.xml"
[INFO]    controller: "window.js"
[INFO]    created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/window.js"
[INFO]    created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/window.js"
[INFO]  [widget.xml] yy.alert view processing...
[INFO]    style:      "widget.tss"
[INFO]    view:       "widget.xml"
[INFO]    controller: "widget.js"
[INFO]    created:    "Resources/iphone/alloy/widgets/yy.alert/controllers/widget.js"
[INFO]    created:     "Resources/iphone/alloy/widgets/yy.alert/styles/widget.js"
[INFO]  [index.xml] view processing...
[INFO]    style:      "index.tss"
[INFO]    view:       "index.xml"
[INFO]    controller: "index.js"
[ERROR] ",
[ERROR]   
[ERROR] (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:189:18)
[ERROR] (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:197:11)
[ERROR] (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:664:9)
[ERROR] Alloy compiler failed
```

**Comment by dbankier** [comment]
not sure. can you see if there is anything odd in the generated app/controllers/index.js file?

**Comment by Pinesy** [comment]
Here is the generated index.js

```javascript
"use strict";

var $model = {};
nano($, $model);
$.index.open();

function login() {
  Alloy.Globals.loading.show("Loading...", false);
  if (true) {
    Alloy.Globals.alert.show({
      title: "JAST",
      message: JSON.stringify($model)
    });
    Alloy.Globals.loading.hide();
    return;
  }
  Alloy.Globals.xhrGet("/login", function (res) {
    Alloy.Globals.loading.hide();
  }, function (res) {
    Alloy.Globals.loading.hide();
    Alloy.Globals.alert.show({
      title: "Error",
      message: "Could not Login"
    });
  });
}
```

**Comment by dbankier** [comment]
what version of alloy are you running?

**Comment by Pinesy** [comment]
Ran `grunt clean` and just did `ti build -p ios --appify` and it works... odd. 

However, then after running `grunt dev -p ios` in a new tab(is it supposed to be in a new tab?), it gives me this output:

```
± |master ✓| → grunt dev -p ios
Running "copy:alloy" (copy) task
Created 45 directories, copied 157 files

Running "jade:compile" (jade) task
File "app/views/index.xml" created.

Running "stss:compile" (stss) task
File "app/styles/app.tss" created.
File "app/styles/index.tss" created.

Running "6to5:dist" (6to5) task

Running "concurrent:run" (concurrent) task
Running "tishadow:run" (tishadow) task
Running "watch:javascripts" (watch) task
Waiting...Running "watch:styles" (watch) task
Waiting...Running "watch:views" (watch) task
Waiting...TiShadow REPL

launchApp(appName), closeApp(), runSpec() and clearCache() methods available.
require(), Ti.include() and assests are relative the running app.


> [INFO] Beginning Build Process
[INFO] Compiling Alloy for ios
[INFO] [iphone, 8.1, 192.168.0.7] Connected
[INFO]  [config.json] regenerating CFG.js from config.json...
[INFO] ----- MVC GENERATION -----
[INFO] [app.tss] global style processing...
[INFO] [global style] writing to cache...
[INFO] [view.xml] nl.fokkezb.loading view processing...
[INFO]   style:      "view.tss"
[INFO]   view:       "view.xml"
[INFO]   controller: "view.js"
[INFO]   created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/view.js"
[INFO]   created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/view.js"
[INFO] [widget.xml] nl.fokkezb.loading view processing...
[INFO]   view:       "widget.xml"
[INFO]   controller: "widget.js"
[INFO]   created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/widget.js"
[INFO]   created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/widget.js"
[INFO] [window.xml] nl.fokkezb.loading view processing...
[INFO]   style:      "window.tss"
[INFO]   view:       "window.xml"
[INFO]   controller: "window.js"
[INFO]   created:    "Resources/iphone/alloy/widgets/nl.fokkezb.loading/controllers/window.js"
[INFO]   created:     "Resources/iphone/alloy/widgets/nl.fokkezb.loading/styles/window.js"
[INFO] [widget.xml] yy.alert view processing...
[INFO]   style:      "widget.tss"
[INFO]   view:       "widget.xml"
[INFO]   controller: "widget.js"
[INFO]   created:    "Resources/iphone/alloy/widgets/yy.alert/controllers/widget.js"
[INFO]   created:     "Resources/iphone/alloy/widgets/yy.alert/styles/widget.js"
[INFO] [index.xml] view processing...
[INFO]   style:      "index.tss"
[INFO]   view:       "index.xml"
[INFO]   controller: "index.js"

/usr/local/lib/node_modules/alloy/Alloy/commands/compile/sourceMapper.js:99
		throw e;
		      ^
Error
    at new JS_Parse_Error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:656:9)
    at token_error (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:664:9)
    at unexpected (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:670:9)
    at expr_atom (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1166:9)
    at maybe_unary (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1327:19)
    at expr_op (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1349:33)
    at expr_ops (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1362:16)
    at maybe_conditional (/usr/local/lib/node_modules/alloy/node_modules/uglify-js/lib/parse.js:1367:20)
[ERROR] Alloy Compile Error
```

**Comment by dbankier** [comment]
I was running alloy of master and just installed the latest from npm and have replicated the issue. Give me a sec.

**Comment by Pinesy** [comment]
No rush, thanks for all your help -- It looks like a very interesting project.

**Comment by dbankier** [comment]
Ahh... yes. I know the problem. You need to use alloy from master to use the `{{ }}` syntax with `nano`. Fixing now.

**Comment by Pinesy** [comment]
Ohh ok. Would you suggest switching to use alloy from master? Or continuing to use the npm version? My team all use the npm version.

**Comment by dbankier** [comment]
OK fixed.

If you want selected alloy compilation (i.e. much faster reloads) then use alloy and tishadow from master.
See https://github.com/dbankier/TiShadow/issues/388 for details.
